# Generated by Django 5.2.14 on 2026-05-19 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artifact', models.TextField()),
                ('checksum', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_packages', to='closure.project')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_id', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('scoreboard', 'Scoreboard'), ('assertion', 'Assertion'), ('coverage', 'Coverage'), ('manual', 'Manual'), ('monitor', 'Monitor'), ('comparison', 'Comparison')], default='scoreboard', max_length=40)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('source_line', models.PositiveIntegerField(blank=True, null=True)),
                ('required_by_default', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='closure.project')),
            ],
            options={
                'ordering': ['test__test_id', 'check_id'],
            },
        ),
        migrations.CreateModel(
            name='RegressionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=160)),
                ('name', models.CharField(blank=True, max_length=220)),
                ('branch', models.CharField(blank=True, max_length=160)),
                ('commit_sha', models.CharField(blank=True, max_length=80)),
                ('tool', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regression_runs', to='closure.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('project', 'run_id')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField()),
                ('schema_version', models.CharField(max_length=20)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_reports', to='closure.project')),
                ('regression_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_reports', to='closure.regressionrun')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requirements', models.PositiveIntegerField(default=0)),
                ('closed_requirements', models.PositiveIntegerField(default=0)),
                ('partial_requirements', models.PositiveIntegerField(default=0)),
                ('failed_requirements', models.PositiveIntegerField(default=0)),
                ('open_requirements', models.PositiveIntegerField(default=0)),
                ('closure_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_snapshots', to='closure.project')),
                ('regression_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_snapshot', to='closure.regressionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='closure.requirementcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='closure.project')),
            ],
            options={
                'verbose_name_plural': 'requirement categories',
                'ordering': ['project', 'display_order', 'code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('spec_section', models.CharField(blank=True, max_length=160)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('rationale', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='closure.project')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='closure.requirementcategory')),
            ],
            options={
                'ordering': ['requirement_id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementCheckMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_for_closure', models.BooleanField(default=True)),
                ('expected_count', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('closure_role', models.CharField(choices=[('proves', 'Proves'), ('observes', 'Observes'), ('covers', 'Covers'), ('guards', 'Guards')], default='proves', max_length=30)),
                ('rationale', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_mappings', to='closure.requirement')),
                ('verification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_mappings', to='closure.check')),
            ],
            options={
                'unique_together': {('requirement', 'verification_check')},
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='checks',
            field=models.ManyToManyField(related_name='requirements', through='closure.RequirementCheckMapping', through_fields=('requirement', 'verification_check'), to='closure.check'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_id', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('directed', 'Directed'), ('constrained_random', 'Constrained random'), ('formal', 'Formal'), ('manual', 'Manual')], default='constrained_random', max_length=40)),
                ('file_path', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='closure.project')),
            ],
            options={
                'ordering': ['test_id'],
                'unique_together': {('project', 'test_id')},
            },
        ),
        migrations.CreateModel(
            name='RequirementTestMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_for_closure', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('proves', 'Proves'), ('stimulates', 'Stimulates'), ('observes', 'Observes'), ('guards', 'Guards'), ('partial', 'Partial')], default='proves', max_length=30)),
                ('rationale', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='closure.requirement')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_mappings', to='closure.test')),
            ],
            options={
                'unique_together': {('requirement', 'test')},
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='tests',
            field=models.ManyToManyField(related_name='requirements', through='closure.RequirementTestMapping', to='closure.test'),
        ),
        migrations.AddField(
            model_name='check',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='closure.test'),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('seed', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=400)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('regression_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='closure.regressionrun')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='closure.test')),
            ],
            options={
                'ordering': ['test_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=160)),
                ('expected', models.BooleanField(default=True)),
                ('observed', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('missing', 'Missing'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('verification_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='closure.check')),
                ('regression_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_evidence', to='closure.regressionrun')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_evidence', to='closure.requirement')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_evidence', to='closure.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('partial', 'Partial'), ('open', 'Open'), ('failed', 'Failed'), ('missing', 'Missing')], default='open', max_length=20)),
                ('expected_checks_count', models.PositiveIntegerField(default=0)),
                ('passed_checks_count', models.PositiveIntegerField(default=0)),
                ('failed_checks_count', models.PositiveIntegerField(default=0)),
                ('missing_checks_count', models.PositiveIntegerField(default=0)),
                ('expected_tests_count', models.PositiveIntegerField(default=0)),
                ('passed_tests_count', models.PositiveIntegerField(default=0)),
                ('failed_tests_count', models.PositiveIntegerField(default=0)),
                ('missing_tests_count', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('regression_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_evidence', to='closure.regressionrun')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='closure.requirement')),
            ],
            options={
                'ordering': ['requirement__requirement_id'],
                'unique_together': {('regression_run', 'requirement')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('project', 'requirement_id')},
        ),
        migrations.AlterUniqueTogether(
            name='check',
            unique_together={('project', 'test', 'check_id')},
        ),
    ]
